; Meshtastic based on ESP32-WROOM-32 & SX1262/SX1268 modules (featherwing lora rfm9x)
[env:meshtastic_diy_featherwroom]
extends = esp32_base
board = esp32doit-devkit-v1
board_level = extra
build_flags =
  ${esp32_base.build_flags}
  -D DIY_V1
  -D EBYTE_E22
  -I variants/esp32/diy/meshtastic_diy_featherwroom
